### ISSUE TITLE
Failed to connect to serial port

### ISSUE THREAD

**Issue by Marc1200** [eddso/ha_iec6205621#1]
i cannot connect to the serial port of the smart meter in home assistant, i says failed to connect. 
i use this meter: https://shop.weidmann-elektronik.de/index.php?page=product&info=24. 

i can see the usb-uart converter in terminal when i execute dmesg.

![image](https://user-images.githubusercontent.com/68737063/202325136-dbdee213-c9d0-48f1-b034-5c0176b833fb.png)

**Comment by eddso** [comment]
* enable debug and check whats going on
* this integration support only IEC 62056-21 protocol [mode B](https://github.com/lvzon/dsmr-p1-parser/blob/master/doc/IEC-62056-21-notes.md), do you have such a meter? In my case i have PAFAL meter.

**Comment by Marc1200** [comment]
Okay, i dont know if my meter support mode b.
I have the kaifa mb310h4bnl5

**Comment by eddso** [comment]
I think it's DSMR protocoll. Take this Integration https://www.home-assistant.io/integrations/dsmr/.
Also search here https://community.home-assistant.io/search for Kaifa.
Maybe also here for User Manuals https://www.kaifametering.com/product_lists/8.html

**Comment by Marc1200** [comment]
okay, i will try it, thanks for the information
